package org.bridj.cpp.com.dispatch;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Name;
import org.bridj.cpp.com.IUnknown;

/*
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Name("tagCONNECTDATA")
public class CONNECTDATA extends StructObject {
	static {
		BridJ.register();
	}

	/*
	 * C type : IUnknown*
	 */
	@Field(0)
	public Pointer<IUnknown> pUnk() {
		return this.io.getPointerField(this, 0);
	}

	/*
	 * C type : IUnknown*
	 */
	@Field(0)
	public CONNECTDATA pUnk(Pointer<IUnknown> pUnk) {
		this.io.setPointerField(this, 0, pUnk);
		return this;
	}

	@Field(1)
	public int dwCookie() {
		return this.io.getIntField(this, 1);
	}

	@Field(1)
	public CONNECTDATA dwCookie(int dwCookie) {
		this.io.setIntField(this, 1, dwCookie);
		return this;
	}
}
