package org.bridj.cpp.com.dispatch;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.ann.Name;
import org.bridj.ann.Virtual;
import org.bridj.cpp.com.GUID;
import org.bridj.cpp.com.IUnknown;
import org.bridj.cpp.com.idl.In;
import org.bridj.cpp.com.idl.Out;

/*
 * <i>native declaration : line 2</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@org.bridj.cpp.com.IID("B196B284-BAB4-101A-B69C-00AA00341D07")
@Name("IConnectionPointContainer")
public class IConnectionPointContainer extends IUnknown {
	static {
		BridJ.register();
	}
	/*
	 * Original signature : <code>HRESULT EnumConnectionPoints(IEnumConnectionPoints**)</code><br>
	 * <i>native declaration : line 6</i>
	 */
	@Name("EnumConnectionPoints")
	@Virtual(0)
	public native int EnumConnectionPoints(@Out Pointer<Pointer<IEnumConnectionPoints> > ppEnum);
	/*
	 * Original signature : <code>HRESULT FindConnectionPoint(const IID&, IConnectionPoint**)</code><br>
	 * <i>native declaration : line 9</i>
	 */
	@Name("FindConnectionPoint")
	@Virtual(1)
	public native int FindConnectionPoint(@In Pointer<GUID> riid,@Out Pointer<Pointer<IConnectionPoint> > ppCP);
}
