package org.bridj.cpp.com.dispatch;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.ann.Name;
import org.bridj.ann.Virtual;
import org.bridj.cpp.com.GUID;
import org.bridj.cpp.com.IUnknown;
import org.bridj.cpp.com.idl.In;
import org.bridj.cpp.com.idl.Out;

/*
 * <i>native declaration : line 2</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@org.bridj.cpp.com.IID("B196B286-BAB4-101A-B69C-00AA00341D07")
@Name("IConnectionPoint")
public class IConnectionPoint extends org.bridj.cpp.com.IUnknown {
	static {
		BridJ.register();
	}

	/*
	 * Original signature : <code>HRESULT GetConnectionInterface(IID*)</code><br>
	 * <i>native declaration : line 6</i>
	 */
	@Name("GetConnectionInterface")
	@Virtual(0)
	public native int GetConnectionInterface(@In Pointer<GUID> pIID);

	/*
	 * Original signature : <code>HRESULT GetConnectionPointContainer(IConnectionPointContainer**)</code><br>
	 * <i>native declaration : line 9</i>
	 */
	@Name("GetConnectionPointContainer")
	@Virtual(1)
	public native int GetConnectionPointContainer(@Out Pointer<Pointer<IConnectionPointContainer>> ppCPC);

	/*
	 * Original signature : <code>HRESULT Advise(IUnknown*, DWORD*)</code><br>
	 * <i>native declaration : line 12</i>
	 */
	@Name("Advise")
	@Virtual(2)
	public native int Advise(@In Pointer<IUnknown> pUnkSink, @Out Pointer<Integer> pdwCookie);

	/*
	 * Original signature : <code>HRESULT Unadvise(DWORD)</code><br>
	 * <i>native declaration : line 16</i>
	 */
	@Name("Unadvise")
	@Virtual(3)
	public native int Unadvise(@In int dwCookie);

	/*
	 * Original signature : <code>HRESULT EnumConnections(IEnumConnections**)</code><br>
	 * <i>native declaration : line 19</i>
	 */
	@Name("EnumConnections")
	@Virtual(4)
	public native int EnumConnections(@Out Pointer<Pointer<IEnumConnections>> ppEnum);
}
